export enum UserRole {
  USER = 'user',
  ADMIN = 'admin',
}

export class User {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly email: string,
    public readonly password: string,
    public readonly role: UserRole = UserRole.USER,
  ) {}

  static create(data: {
    name: string;
    email: string;
    password: string;
    role?: UserRole;
  }): User {
    return new User(
      '', // ID will be generated by MongoDB
      data.name,
      data.email,
      data.password,
      data.role ?? UserRole.USER,
    );
  }

  toJSON() {
    return {
      id: this.id,
      name: this.name,
      email: this.email,
      role: this.role,
    };
  }
}
