version: '3.8'

services:
  app-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongodb-test:27017/example_test
      - JWT_SECRET=test-secret-key
    depends_on:
      - mongodb-test
    networks:
      - test-network
    volumes:
      - ..:/app
      - /app/node_modules

  mongodb-test:
    image: mongo:7.0
    ports:
      - '27018:27017'
    volumes:
      - mongodb_test_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=example_test
    networks:
      - test-network

  redis-test:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    volumes:
      - redis_test_data:/data
    networks:
      - test-network

volumes:
  mongodb_test_data:
  redis_test_data:

networks:
  test-network:
    driver: bridge
