export enum TodoStatus {
  PENDING = 'pending',
  IN_PROGRESS = 'in-progress',
  DONE = 'done',
}

export class Todo {
  constructor(
    public readonly id: string,
    public readonly title: string,
    public readonly description: string,
    public readonly status: TodoStatus,
    public readonly ownerId: string,
  ) {}

  static create(data: {
    title: string;
    description?: string;
    status?: TodoStatus;
    ownerId: string;
  }): Todo {
    return new Todo(
      '', // ID will be generated by MongoDB
      data.title,
      data.description ?? '',
      data.status ?? TodoStatus.PENDING,
      data.ownerId,
    );
  }

  updateStatus(status: TodoStatus): Todo {
    return new Todo(
      this.id,
      this.title,
      this.description,
      status,
      this.ownerId,
    );
  }

  updateContent(title: string, description?: string): Todo {
    return new Todo(
      this.id,
      title,
      description ?? this.description,
      this.status,
      this.ownerId,
    );
  }

  toJSON() {
    return {
      id: this.id,
      title: this.title,
      description: this.description,
      status: this.status,
      ownerId: this.ownerId,
    };
  }
}
